### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by RogerPhilippe** [RogerPhilippe/fiap_trabalho_flutter#1]
-  Desenvolvimento de uma aplicação Flutter que contenha pelo menos 9 dos 12 conceitos vistos em aula:

- [x] Widgets
- [x] States
- [ ] Banco de dados NoSQL
- [x] Banco de dados Sqlite
- [ ] Push Notification com FCM
- [x] Banco de dados Firebase
- [ ] Mapas
- [x] Platform Channel
- [x] Provider
- [x] MobX
- [x] GetIt
- [x] Conectividade HTTP

- Grupos de 1 até 4 pessoas.
Envio do trabalho final até dia 30/09/2020, às 23:59. - Adiado para 11.09.2020
Envio de:
   * Link para o código fonte no GitHub.
   * Documento (doc ou pdf) descrevendo o aplicativo.
   * Vídeo mostrando o aplicativo em funcionamento.
